Repository planetarium/UniLibplanet, pull requests merged in 2022-06, with the labels that each got.

#1 Setting .env
  .env.xml.sample
  .gitignore
  Libplanet.Unity/Libplanet.Unity.csproj
  Libplanet.Unity/UnityReference/.gitignore
  README.md
  libplanet-unity-sdk.sln
  scripts/create-dotenv.ps1
Labels: Small

#3 Fix Libplanet.Unity Description
  Libplanet.Unity/LICENSE
  Libplanet.Unity/README.md
  Libplanet.Unity/package.json
Labels: Extra Large

#4 Fix packagename
  Libplanet.Unity/package.json
Labels: Extra Small

#7 Renaming
  Unilibplanet/.gitignore
  Unilibplanet/Assets/Editor.meta
  Unilibplanet/Assets/Editor/PackageExporter.cs
  Unilibplanet/Assets/Editor/PackageExporter.cs.meta
  Unilibplanet/Assets/Libplanet.Unity.meta
  Unilibplanet/Assets/Libplanet.Unity/ActionBase.cs
  Unilibplanet/Assets/Libplanet.Unity/ActionBase.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Agent.cs
  Unilibplanet/Assets/Libplanet.Unity/Agent.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Editor.meta
  Unilibplanet/Assets/Libplanet.Unity/Editor/BlockChainMenu.cs
  Unilibplanet/Assets/Libplanet.Unity/Editor/BlockChainMenu.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Editor/GenesisBlockMenu.cs
  Unilibplanet/Assets/Libplanet.Unity/Editor/GenesisBlockMenu.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Editor/PrivateKeyMenu.cs
  Unilibplanet/Assets/Libplanet.Unity/Editor/PrivateKeyMenu.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Editor/SwarmConfigMenu.cs
  Unilibplanet/Assets/Libplanet.Unity/Editor/SwarmConfigMenu.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Editor/UtilsMenu.cs
  Unilibplanet/Assets/Libplanet.Unity/Editor/UtilsMenu.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Libplanet.Unity.asmdef
  Unilibplanet/Assets/Libplanet.Unity/Libplanet.Unity.asmdef.meta
  Unilibplanet/Assets/Libplanet.Unity/Miner.cs
  Unilibplanet/Assets/Libplanet.Unity/Miner.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/MonoSingleton.cs
  Unilibplanet/Assets/Libplanet.Unity/MonoSingleton.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Paths.cs
  Unilibplanet/Assets/Libplanet.Unity/Paths.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/SwarmRunner.cs
  Unilibplanet/Assets/Libplanet.Unity/SwarmRunner.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/Utils.cs
  Unilibplanet/Assets/Libplanet.Unity/Utils.cs.meta
  Unilibplanet/Assets/Libplanet.Unity/package.json
  Unilibplanet/Assets/Libplanet.Unity/package.json.meta
  Unilibplanet/Assets/Plugins.meta
  Unilibplanet/ProjectSettings/AudioManager.asset
  Unilibplanet/ProjectSettings/ClusterInputManager.asset
  Unilibplanet/ProjectSettings/DynamicsManager.asset
  Unilibplanet/ProjectSettings/EditorBuildSettings.asset
  Unilibplanet/ProjectSettings/EditorSettings.asset
  Unilibplanet/ProjectSettings/GraphicsSettings.asset
  Unilibplanet/ProjectSettings/InputManager.asset
  Unilibplanet/ProjectSettings/MemorySettings.asset
  Unilibplanet/ProjectSettings/NavMeshAreas.asset
  Unilibplanet/ProjectSettings/PackageManagerSettings.asset
  Unilibplanet/ProjectSettings/Physics2DSettings.asset
  Unilibplanet/ProjectSettings/PresetManager.asset
  Unilibplanet/ProjectSettings/ProjectSettings.asset
  Unilibplanet/ProjectSettings/ProjectVersion.txt
  Unilibplanet/ProjectSettings/QualitySettings.asset
  Unilibplanet/ProjectSettings/TagManager.asset
  Unilibplanet/ProjectSettings/TimeManager.asset
  Unilibplanet/ProjectSettings/UnityConnectSettings.asset
  Unilibplanet/ProjectSettings/VFXManager.asset
  Unilibplanet/ProjectSettings/VersionControlSettings.asset
  Unilibplanet/ProjectSettings/boot.config
  scripts/build-libplanet.ps1
  scripts/build-unity.ps1
  unilibplanet.sln
Labels: Extra Small

#9 Rollback Libplanet.Unity
  Libplanet.Unity/ActionBase.cs
  Libplanet.Unity/Agent.cs
  Libplanet.Unity/Libplanet.Unity.csproj
  Libplanet.Unity/Miner.cs
  Libplanet.Unity/MonoSingleton.cs
  Libplanet.Unity/Paths.cs
  Libplanet.Unity/SwarmRunner.cs
  Libplanet.Unity/Utils.cs
  UniLibplanet.sln
  UniLibplanet/Assembly-CSharp-Editor.csproj
  UniLibplanet/Assets/Editor.meta
  UniLibplanet/Assets/Editor/PackageExporter.cs
  UniLibplanet/Assets/Libplanet.Unity/ActionBase.cs.meta
  UniLibplanet/Assets/Libplanet.Unity/Agent.cs.meta
  UniLibplanet/Assets/Libplanet.Unity/Editor/PrivateKeyMenu.cs.meta
  UniLibplanet/Assets/Libplanet.Unity/Editor/SwarmConfigMenu.cs.meta
  UniLibplanet/Assets/Libplanet.Unity/Libplanet.Unity.asmdef
  UniLibplanet/Assets/Libplanet.Unity/Miner.cs.meta
  UniLibplanet/Assets/Libplanet.Unity/MonoSingleton.cs.meta
  UniLibplanet/Assets/Libplanet.Unity/Utils.cs.meta
  UniLibplanet/Assets/Libplanet.Unity/package.json.meta
  UniLibplanet/Assets/Plugins.meta
  UniLibplanet/Assets/Scripts.meta
  UniLibplanet/Assets/Scripts/Libplanet.Unity.meta
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor.meta
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/BlockChainMenu.cs
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/BlockChainMenu.cs.meta
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/GenesisBlockMenu.cs
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/GenesisBlockMenu.cs.meta
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/PrivateKeyMenu.cs
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/PrivateKeyMenu.cs.meta
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/SwarmConfigMenu.cs
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/SwarmConfigMenu.cs.meta
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/UtilsMenu.cs
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/UtilsMenu.cs.meta
  UniLibplanet/Assets/package.json
  UniLibplanet/Assets/package.json.meta
  scripts/build-libplanet.ps1
  scripts/build-unity.ps1
Labels: Extra Large

#10 Editor updated
  .gitignore
  UniLibplanet/.gitignore
  UniLibplanet/Assembly-CSharp-Editor.csproj
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/GenesisBlockMenu.cs
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/PrivateKeyMenu.cs
  UniLibplanet/Assets/Scripts/Libplanet.Unity/Editor/SwarmConfigMenu.cs
Labels: Extra Large

#12 UpdateREADME.md, Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: Small

#13 Separate ActionWorker
  Libplanet.Unity/ActionWorker.cs
  Libplanet.Unity/Agent.cs
Labels: Small

#15 `GetState` overload added
  Libplanet.Unity/Agent.cs
Labels: Extra Small

#14 Delete MonoSingleton
  Libplanet.Unity/Agent.cs
  Libplanet.Unity/MonoSingleton.cs
Labels: Small

#16 Revert back to 81c6993
  Libplanet.Unity/ActionWorker.cs
  Libplanet.Unity/Agent.cs
  Libplanet.Unity/MonoSingleton.cs
Labels: Medium

#17 GetState overload added
  Libplanet.Unity/Agent.cs
Labels: Extra Small

#18 `MakeTransaction()` parameter type changed
  Libplanet.Unity/Agent.cs
Labels: Extra Small

#20 Refactor miner
  Libplanet.Unity/Agent.cs
  Libplanet.Unity/Miner.cs
Labels: Extra Small

#21 Refactor action worker
  Libplanet.Unity/ActionWorker.cs
  Libplanet.Unity/Agent.cs
  Libplanet.Unity/SwarmRunner.cs
Labels: Extra Small

#28 Add Build SDK Menu
  UniLibplanet/Assets/Editor/PackageExporter.cs
Labels: Extra Small

#29 Show required version of SDK on README
  README.md
Labels: Extra Small
