Repository planetarium/UniLibplanet, pull requests merged in 2022-07, with the labels that each got.

#34 `Agent` is no more singleton
  Libplanet.Unity/Agent.cs
  Libplanet.Unity/Libplanet.Unity.csproj
  Libplanet.Unity/MonoSingleton.cs
  README.md
  UniLibplanet.sln
  scripts/build-libplanet.ps1
  scripts/build-unity.ps1
  scripts/build.ps1
  scripts/create-dotenv.ps1
Labels: Medium

#35 Delete development
  Libplanet.Unity/ActionWorker.cs
  Libplanet.Unity/Agent.cs
  Libplanet.Unity/Miner.cs
  Libplanet.Unity/SwarmRunner.cs
  UniLibplanet/Assets/Editor/PackageExporter.cs
Labels: Small

#41 Make that events invoked in coroutines get invoked within the main thread
  docs/basic_node.md
  docs/click_counter.md
  docs/scoreboard.md
Labels: Extra Small

#48 Update `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: documentation
